### ISSUE TITLE
Test the OpenSPP modules that are migrated to Odoo 17

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#431] opened 2024-05-29 03:35 UTC
1. No unique ID for Group and Individual
Ticket: [Improve odoo import for registrant #247](https://github.com/OpenSPP/openspp-modules/issues/247)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/2668ce7d-1e5f-42e0-b557-baf79220d2ce)
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/27e77f4b-dc8b-44c2-bcca-b7324210908a)

2. No **Import Match**, no **Custom Fields**, no **Country Office** in Registry > Configuration
Tickets: 
- [Extend Importing Function with the Import Matching #5](https://github.com/OpenSPP/openspp-base/issues/5)
- [Add a way to recompute the indicator fields that are set to be recomputed daily #216](https://github.com/OpenSPP/openspp-modules/issues/216)
- [Create a module that allow to create country office (aka company in odoo) and configure it #3](https://github.com/OpenSPP/newlogic-sp/issues/3)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/5e412957-aa1c-4f29-a3a1-06335af049ce)

3. No import in the background checkbox on the left side of the screen when importing a file.
Ticket: [Improve the odoo import to support async #1](https://github.com/OpenSPP/openspp-base/issues/1)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/e7caad06-ca05-458c-9637-b36359963fc5)

4. No top-up card or any cards in Individuals and Groups
Ticket: [Extend ID Document to support top-up card #249](https://github.com/OpenSPP/openspp-modules/issues/249)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/394b1a0d-ad13-4a0d-bdd7-3caced564fec)
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/62b4a888-0b18-47cf-8982-dd673400ad7e)

5. No Program ID
Ticket: [Add a field program_id to each program. It is a string auto generated with the format: PROG_{SEQ} #88](https://github.com/OpenSPP/openspp-program/issues/88)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/42e13fdd-0b51-4d7b-abe6-db173a606d33)

6. No **SQL-based Eligibility Manager**, no **Tag-based Eligibility Manager**, no **Compliance Criteria** in Set Program Settings
Tickets:
- [implement a SQL eligibility manager #89](https://github.com/OpenSPP/openspp-program/issues/89)
- [Add a new enrollment manager that is based on tag+Area #86](https://github.com/OpenSPP/openspp-program/issues/86)
- [Implement compliance criteria #90](https://github.com/OpenSPP/openspp-program/issues/90)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/e479dbea-7dc8-492a-a8f0-cbb2ab580cb9)

7. No **Store Service Points to Entitlements** checkbox in Entitlement Manager 
Tickets: 
- [Implement different way to associate service points to entitlements #83](https://github.com/OpenSPP/openspp-program/issues/83)
- [Enhance API and UI to Filter Service Points by Program #64](https://github.com/OpenSPP/openspp-api/issues/64)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/4fd1096e-b135-456b-83a4-3b693bd72698)

8. No local and global roles
Ticket: [Standardize user roles #2](https://github.com/OpenSPP/openspp-base/issues/2)

9. No unique ID for Area and Service Points
Ticket: [create unique id on areas & service points for integrate with OpenFN #273](https://github.com/OpenSPP/openspp-modules/issues/273)

10. No **Contacts**, no **OpenAPI** in Home Menu
Tickets:
- [Associate a company and contacts to each service point. #245](https://github.com/OpenSPP/openspp-modules/issues/245)
- [Setting up Swagger documentation for the APIs #70](https://github.com/OpenSPP/openspp-api/issues/70)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/9421ef3a-4593-449e-b38e-2b87802fab27)

11. No **Import from Registry** in Registry for the OpenCRVS Integration
Ticket: [G2P Connect API Implementation - OpenCRVS Integration #67](https://github.com/OpenSPP/openspp-api/issues/67)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/e0c9613f-32d8-4904-8276-8268a9340e61)

12. No DCI API Client Credentials in Settings
Ticket: [G2P Connect API Implementation - OpenCRVS Integration #67](https://github.com/OpenSPP/openspp-api/issues/67)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/759a2477-0bc7-41e6-8eaa-957ab886a8a5)

13. No option to add negative criteria
Ticket: [In the enrollment module, Add an option to add negative criterias #18](https://github.com/OpenSPP/openspp-program/issues/18)

14. Amount per Cycle column behavior in Entitlement Manager for Cash
https://drive.google.com/file/d/198GySHEb4zXhfbOU4gDQdP1wDbwajlKX/view?usp=sharing

15. No **Approve Entitlements** button for In-kind Entitlements (unlike in Cash), resulting to **Approved** state but entitlements are still in **Pending Validation**.
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/03e27cb0-ace1-4ce4-a36c-bfc515095477)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/47643b98-38d3-4316-8971-5c3ad186eac1)

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/f80eb648-38c0-4641-9b2d-fe82195e06c7)

16. PMT Score of Group is not updating when Default Weight is changed.
https://drive.google.com/file/d/1dDbUqWkwmMU3ltsR8mxZBRMQBoL9rUZh/view?usp=sharing

17. Random error message appears in Custom Fields.

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1765, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1792, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1996, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/web/models/models.py", line 76, in web_save
    return self.with_context(bin_size=True).web_read(specification)
  File "/opt/odoo/auto/addons/web/models/models.py", line 86, in web_read
    values_list: List[Dict] = self.read(fields_to_read, load=None)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3539, in read
    self._origin.fetch(fields)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3827, in fetch
    fetched = self._fetch_query(query, fields_to_fetch)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3940, in _fetch_query
    field.read(fetched)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 4821, in read
    query.order = comodel._order_to_sql(comodel._order, query)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5163, in _order_to_sql
    term = self._order_field_to_sql(alias, field_name, sql_direction, sql_nulls, query)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5184, in _order_field_to_sql
    raise ValueError(f"Invalid field {field_name!r} on model {self._name!r}")
ValueError: Invalid field 'id' on model '_unknown'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://acf-dev.newlogic-demo.com/web/assets/fc5753c/web.assets_web.min.js:2879:163)
    at XMLHttpRequest.<anonymous> (https://acf-dev.newlogic-demo.com/web/assets/fc5753c/web.assets_web.min.js:2883:13)

18. Cannot delete a Rule in Audit Rule page.

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1765, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1792, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1996, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/spp_audit_log/models/spp_audit_rule.py", line 177, in unlink
    audit_rule_count = self.env["spp.audit.rule"].search(
TypeError: BaseModel.search() got an unexpected keyword argument 'count'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:27818:19)
    at XMLHttpRequest.<anonymous> (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:27866:27)

19. Error message when clicking View Logs.
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/c29353c5-9722-4356-b493-24e5e26ecb72)

20. In Programs  > Configuration > General Settings > Program Settings. 
No Setting Found error is still displaying even when Program Setting is already clicked.
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/44ada90d-494c-47f7-91d4-7f145e30520a)

21. Select a Program with Compliance Criteria. Click Configuration. Scroll down to Compliance Manager.
The Compliance is not displayed properly.
https://github.com/OpenSPP/openspp-modules/assets/138551361/4cfa5070-787f-4ed4-bee8-13e02f2aefb6

22. SQL Record Count is always zero in Compliance Criteria
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/a6919b3d-5b40-4cba-82ba-f88479233427)

**Comment by dasunhegoda** [comment] 2024-05-29 03:51
@celinenilla @adriancris : These are core functionalities that need to be fixed before the release. So I added the ticket to the iteration 21.

**Comment by jeremi** [comment] 2024-05-30 03:25
> 1. No unique ID for Group and Individual
>    Ticket: [Improve odoo import for registrant #247](https://github.com/OpenSPP/openspp-modules/issues/247)

@dasunhegoda what is the issue with this? I think it has been implemented, no?

**Comment by dasunhegoda** [comment] 2024-05-31 02:16
It has been implemented but it's not showing in the UI after the Odoo 17 update @jeremi.

**Comment by reichie020212** [comment] 2024-06-06 06:01
@dasunhegoda I did a quick investigation on these issues and here are my comments per issues

1. Install "OpenSPP: Import Improvement"
2. - for Import Match, Install "OpenSPP Import Matching"
- for Custom Fields, Install "OpenSPP Custom Field: Recompute Daily"
- for Country Office, Install "OpenSPP Base Settings"
4. Install "OpenSPP Base" 
5. Install "OpenSPP Programs: Import"
6. Install the following modules:
- OpenSPP SQL Query Eligibility Manager
- OpenSPP Tag Based Eligibility Manager
- OpenSPP Programs: Compliance Criteria
7. Install "OpenSPP Programs (Service Points Integration)"
8. Install User Roles Management
9. Install "OpenSPP: Import Improvement"
10. - for the OpenAPI, just install "OpenSPP REST API"
- for the Contacts, it will be hidden if the module "OpenSPP Theme (Muk Theme)" is installed, but you can unhide the Contacts by going to Settings -> Users & Companies -> Users -> select current user -> Access Rights -> Check the access right "Hide Menu" then save
11. The "Import From Registry" is not located in Registry but in the Program. Install "OpenSPP Import: DCI API".
12. Install "OpenSPP API: DCI Server"
13. Install "OpenSPP Create Program Wizard Exclusion"

15 . Already tackled on this ticket: https://github.com/OpenSPP/openspp-modules/issues/420
18 . Need to fix the audit module to accomodate the changes from Odoo 15 to Odoo 17
19 . Need to investigate and fix the audit module.

Other issues that are missing in my comment is either I am not familiar on those issue or needs a thorough investigation.

**Comment by adriancris** [comment] 2024-06-06 06:37
Checking @reichie020212's comments

**Comment by reichie020212** [comment] 2024-06-06 06:47
@dasunhegoda I Tackled issue 18 and issue 19 about audit log in this ticket https://github.com/OpenSPP/openspp-modules/issues/436

**Comment by adriancris** [comment] 2024-06-09 10:49
This is a reply to @reichie020212's investigation.

1. OpenSPP: Import Improvement - Installed

2. OpenSPP Import Matching - Installed
OpenSPP Custom Field: Recompute Daily - Installed
OpenSPP Base Settings - Installed

4. OpenSPP Base - Installed

5. OpenSPP Programs: Import - Installed

6. OpenSPP SQL Query Eligibility Manager - Installed
OpenSPP Tag Based Eligibility Manager - Installed
OpenSPP Programs: Compliance Criteria - Installed

7. OpenSPP Programs (Service Points Integration) - Installed

8. User Roles Management - Cannot install - #444 

9. OpenSPP: Import Improvement - Installed

10. OpenSPP REST API - Cannot install - #445 

11. OpenSPP Import: DCI API - Cannot install - #446 

12. OpenSPP API: DCI Server - Cannot install - #447 

13. OpenSPP Create Program Wizard Exclusion - Installed

**Comment by reichie020212** [comment] 2024-06-10 03:30
@dasunhegoda here are some additional comments of some issues

issue 21: I fixed the UI issue and i created a new ticket for this https://github.com/OpenSPP/openspp-modules/issues/451
issue 22: Upon checking, "Validate Query" needs to click first to update the record count

**Comment by adriancris** [comment] 2024-06-11 14:17
hi @reichie020212 
*
*
*
issue 22: Upon checking, "Validate Query" needs to click first to update the record count
*
*
*
After clicking Validate Query, the record count is updated. But the modal closes. Is that expected behavior?

https://github.com/OpenSPP/openspp-modules/assets/138551361/5316c8eb-26f1-483c-9a22-661c7d722fc8

**Comment by reichie020212** [comment] 2024-06-13 01:51
hi @adriancris , i'm not sure if this is a expected behaviour since i'm not the one who built this but i'll try to ask @gonzalesedwin1123 or @emjay0921 .

**Comment by emjay0921** [comment] 2024-07-22 06:57
This is the expected behavior as the form being viewed here is not a wizard.

**Comment by anthonymarkQA** [comment] 2024-07-24 07:40
ACF DEV
FINDINGS: Returned to dev

failed items:
3, 8, 9, 14, 16, 20

1 no unique ID for group and individual - pass
2 No Import Match, no Custom Fields, no Country Office in Registry > Configuration
Tickets: - pass
**3 No import in the background checkbox on the left side of the screen when importing a file. - FAIL**
4.No top-up card or any cards in Individuals and Groups - pass
5.No program ID -pass
6.No SQL-based Eligibility Manager, no Tag-based Eligibility Manager, no Compliance Criteria in Set Program Settings - pass
7.No Store Service Points to Entitlements checkbox in Entitlement Manager
Tickets: - pass
**8.No local and global roles - Fail, roles are not working when logged in.**
**9.No unique ID for Area and Service Points - 
Service points- pass
Area - fail , no label and its placement is off.**
10.No contacts, no OpenAPI in home menu - pass
11.No Import from Registry in Registry for the OpenCRVS Integration - pass
12 No DCI API Client Credentials in Settings -  pass
13. No option to add negative criteria - pass
14. amount per cycle in cash - fail. layout is inconsistent, you can drag it side to side and distort it
15. No Approve Entitlements button for In-kind Entitlements (unlike in Cash), resulting to Approved state but entitlements are still in Pending Validation. - pass
16. PMT Score of Group is not updating when Default Weight is changed. -Fail . no changes when tweaking default weight from pmt score
17. Random error message appears in Custom Fields. -pass
18 Cannot delete a Rule in Audit Rule page. - pass
19 Error message when clicking View Logs. - pass
**20.In Programs > Configuration > General Settings > Program Settings.
No Setting Found error is still displaying even when Program Setting is already clicked. - FAIL. still existing**
21.Select a Program with Compliance Criteria. Click Configuration. Scroll down to Compliance Manager.
The Compliance is not displayed properly. - pass
22.SQL Record Count is always zero in Compliance Criteria - pass

**Comment by emjay0921** [comment] 2024-07-24 13:26
Item 16 - A change in the default weight won't be able to trigger the function that computes the PMT Score. PMT Score is a stored computed field and would only be triggered if the changes are in the Group's UI directly.

## Possible fixes:
1. Add a function to recompute all PMT Scores of all groups if the default weight is changed - although this is a fix it would not be advisable as this will take a huge load on server if there's a lot of groups in the database.
2. Add a cron job that will create a job queues to recompute the PMT Scores - although this is better than the item before this, the downside is the update of the PMT Scores will be updated synchronously and would have a delay on the update of the PMT Scores of the Groups.
3. Make the PMT Score non-stored - This is the quickest and fastest way to fix this but this needs a clarification and discussion with the team.

**Comment by emjay0921** [comment] 2024-07-24 13:31
Item 3 - I think the Async Importing is not yet adjusted to be supported correctly on Odoo 17. Although there's no error when installing, the problem is the changes of importing structure in the Odoo 17. If it's okay to create new ticket for this as this may take some time to further investigate the issue and modifying the code. This was assigned to me before but nhat is mainly the one who takes this ticket so I might need more time to read and analyze the structure of his codes.

cc: @dasunhegoda , @anthonymarkQA , @celinenilla

**Comment by anthonymarkQA** [comment] 2024-07-29 01:29
Findings: QA passed

Closing this ticket. Issues remaining for this ticket is item 8 and 9. which will be handled on separate tickets..
https://github.com/OpenSPP/openspp-modules/issues/273 - item 9
https://github.com/OpenSPP/openspp-acf/issues/36 -  item 8

**Comment by kneckinator** [comment] 2024-09-25 10:42
@anthonymarkQA the ticket is still open. Please click the Close button if no further changes are expected. Thanks.

**Closed as completed** 2024-09-26 01:15 UTC
