### ISSUE TITLE
Define and edit custom filters in Farmer Registry UI for targeting criterias

### ISSUE THREAD

**Issue by celinenilla** [openspp-project/openspp-registry#669] opened 2024-11-20 06:38 UTC
The targeting criteria in program management need to be enhanced by providing a way to define custom filters in the farmer registry UI.

- [ ] Add a way to define custom filters in the different farmer registry tabs that can be used in targeting criteria
- [ ] Allow editing of the custom filters

**Comment by singhkaranvir25** [comment] 2024-12-11 06:45
Not enough details available. Current description seems to be a duplicate of #642 , hence marking this ticket as won't do. 

This can be re-opened if the scope gets more clear.

**Closed as completed by singhkaranvir25** 2024-12-11 06:45 UTC
