### ISSUE TITLE
Integrate Open-Fn with OpenSPP

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#248] opened 2023-06-22 02:47 UTC
What is OpenFn? 

Digital Public Good for workflow automation–a platform. 

[Video link explaining how OpenFN works](https://www.youtube.com/watch?v=mo4IfBy8wfU)

[Official documentation](https://docs.openfn.org/documentation)

OpenFn v1 iPaaS will be used to integrate with OpenSPP.

- [x] Write the Adaptor
- [x] Prepare a demo flow

registrant_id is from: https://github.com/OpenSPP/openspp-registry/issues/247

Implement the methods:
- [x] getGroup(registrant_id)
- [x] getIndividual(registrant_id)
- [x] searchGroup(domain)
- [x] searchIndividual(domain)
- [x] getGroupMembers(registrant_id)
- [x] getServicePoint(name)
- [x] getPrograms(program_id) https://github.com/OpenSPP/openspp-program/issues/88
- [x] getPrograms()
- [x] getEnrolledPrograms(registrant_id)
- [x] enroll(registrant_id, program_id)
- [x] unenroll(registrant_id, program_id)
- [ ] createChangeRequest(group_id, individual_id, cr_type, data)

**Comment by nhatnm0612** [comment] 2023-06-26 03:35
@jeremi https://community.openfn.org/t/testing-new-adaptor-on-local-environment-with-lightning/331/2
there is no way to test local adaptor on local Lightning running, confirmed by OpenFN employee. I gonna switch to the only way is writing automated tests and running that.

**Comment by jeremi** [comment] 2023-08-08 04:07
ok

**Comment by dasunhegoda** [comment] 2023-08-10 03:39
Left to be done,

- Publishing of the adaptor - create a PR and request them to accept it. @nhatnm0612 will create the PR today.

**Comment by jeremi** [comment] 2023-08-10 04:13
How can I test it manually?

**Comment by nhatnm0612** [comment] 2023-08-10 04:33
@jeremi we can not, only testing using unittest code via `pnpm`, and in term of unittest, I mean mocking test response from Odoo as well.

**Comment by dasunhegoda** [comment] 2023-08-15 03:34
@nhatnm0612 will raise the PR today.

**Comment by jeremi** [comment] 2023-08-16 02:39
but @nhatnm0612 can we install it locally and run it (not automated tests)?

**Comment by nhatnm0612** [comment] 2023-08-16 03:06
> but @nhatnm0612 can we install it locally and run it (not automated tests)?

@jeremi no, it is confirmed by OpenFN employee

**Comment by dasunhegoda** [comment] 2023-09-15 03:44
@nhatnm0612 will setup OpenFN on local to be utilized with OpenSPP repo.

**Comment by dasunhegoda** [comment] 2023-10-16 03:40
@nhatnm0612 has raised a PR in the OpenFN repo. https://github.com/OpenFn/adaptors/pull/409

**Comment by dasunhegoda** [comment] 2023-10-19 03:40
The methods mentioned in the description have been implemented.

**Comment by dasunhegoda** [comment] 2023-10-19 03:42
@nhatnm0612 will list down the steps to setup on local.

**Comment by nhatnm0612** [comment] 2023-10-23 17:11
steps for setting up local OpenFN:

1. Requirements:

- Using Unix like Os [Ubuntu] / MacOs with Apple Silicon chips [harder version].
- Having basic knowledge of nodejs & Unix like file system.

2. Pre-installed:

- [pnpm](https://pnpm.io) & [asdf](https://asdf-vm.com)
- elixir, erlang, nodejs, k6 & phoenix framework for elixir [these will be installed via asdf virtual machine] [doc](https://github.com/OpenFn/Lightning#database-setup) - keep it in mind that I am running local OpenFN Lightning in my MacOS since the docker version does not run on Mac M1
- fixing your local credentials to the Postgres DB to OpenFN Lightning at: https://github.com/OpenFn/Lightning/blob/c057048b56242613d05748a53b352ad0473fd552/config/dev.exs#L4

After Pre-installed step, basically, you can boost up OpenFn Lightning with this command:
`iex -S mix phx.server`

3. Installing new adaptor locally:

- Using mix [elixir] & ecto [elixir] to install dependencies, create DB & migrate
- Copy schemas from new adaptor to be the new schema for OpenSPP login:
      New schema: https://github.com/nhatnm0612/adaptors/blob/add-openspp-adaptor/packages/openspp/configuration-schema.json
      Schemas location: [OpenFNLightningRepo/priv/schemas]
      After this step, boost up OpenFN Lightning and you should see new schema for login.
- Fixing the code of pulling adaptor at: https://github.com/OpenFn/Lightning/blob/c057048b56242613d05748a53b352ad0473fd552/lib/lightning/adaptor_registry.ex#L224
```elixir
  def fetch() do
    start = DateTime.utc_now()
    Logger.debug("Fetching adaptors from NPM.")

    openfn_adapters =
      Npm.user_packages("openfn")
      |> Enum.map(fn {name, _} -> name end)
      |> Enum.filter(fn name ->
        Regex.match?(~r/@openfn\/language-\w+/, name)
      end)
      |> Enum.reject(fn name ->
        name in @excluded_adaptors
      end)
      |> Task.async_stream(
        &fetch_npm_details/1,
        ordered: false,
        max_concurrency: 10,
        timeout: @timeout
      )
      |> Stream.map(fn {:ok, detail} -> detail end)
      |> Enum.to_list()
    result = openfn_adapters ++ [
      %{
        latest: "1.0.0",
        name: "openspp",
        repo: "git+https://github.com/nhatnm0612/adaptors/tree/add-openspp-adaptor",
        versions: [%{version: "1.0.0"}]
      }
    ]
    diff = DateTime.utc_now() |> DateTime.diff(start, :millisecond)
    # IO.inspect(result)
    Logger.debug(fn -> "Finished fetching adaptors in #{diff}ms." end)
    result
  end
```

**Comment by nhatnm0612** [comment] 2023-11-06 02:18
@dasunhegoda due to requests from OpenFN side, I need a rectangle image [png, 512*190px] of OpenSPP for the adaptor logos. [[link]](https://github.com/OpenFn/adaptors/pull/409#discussion_r1376466208). Also, they asked me to create test jobs with OpenSPP sandbox server's credentials [[link]](https://github.com/OpenFn/adaptors/pull/409#pullrequestreview-1713747171)

I made some changes last weekend and all the feedbacks are positive now except these 2.

**Comment by dasunhegoda** [comment] 2023-11-06 13:15
@nhatnm0612 : You can use the logo on our web and resize it as per requirement. If additional help is required, Lit usually helps us with this. We can use the openspp demo env as the sandbox.

**Comment by jeremi** [comment] 2023-11-06 15:45
@nhatnm0612 ask Lit for it. He will prepare it for you.

**Comment by jeremi** [comment] 2023-11-15 04:40
Can you add the methods:
- [x] createIndividual(data)
- [x] updateIndividual(individual_id, data)
- [x] createGroup(data)
- [x] updateGroup(group_id, data)
- [x] addToGroup(group_id, individual_id, role)
- [x] removeFromGroup(group_id, individual_id)

**Comment by nhatnm0612** [comment] 2023-11-27 02:18
[link to slack message](https://newlogic.slack.com/archives/C03DCLRKLN9/p1700797661304779)

- [x] getServicePoint(name) -> getServicePoint(id) **using new field in #273**
- [x] searchServicePoint(domain)
- [x] getArea(id) **using new field in #273**
- [x] searchArea(domain)
- [x] correct docstring for old methods
- [x] create docstring with multi examples

**Closed as completed** 2024-05-15 10:57 UTC
