### ISSUE TITLE
Individual Change Request

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#294] opened 2024-01-17 07:20 UTC
**Description**
- Explore and see how change requests can be supported at the individual level.
- The OCA DMS module is designed to embed itself automatically into all installed modules, regardless of whether they require its functionality. This indiscriminate embedding is leading to significant performance lags, particularly noticeable in large implementations.

**Proposed Solution**
@gonzalesedwin1123 proposed the development of a customized module tailored specifically for the change request module.

**Comment by adriancris** [comment] 2024-04-29 02:07
@gonzalesedwin1123 
Im getting this error when clicking Next

![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/d1a08908-6c7e-495b-bf13-d9d1e85aca42)

**Comment by adriancris** [comment] 2024-04-30 03:23
@gonzalesedwin1123 

**ISSUE**: Odoo Error when clicking a Group that a member has been added to through Change Request.

**STEPS TO REPLICATE**: 
1. Go through the CR process until CR gets validated.
2. Search the member in Registry > Individuals to verify if the member was indeed created.
3. Click the Group the member has been added to in Registry > Groups.

**INSTANCE**: ACF-DEV

**ERROR**:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1768, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1795, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1999, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/web/models/models.py", line 128, in web_read
    vals = many2one_data[values[field_name]]
KeyError: 1

The above server error caused the following client error:
OwlError: The following error occurred in onWillStart: "Odoo Server Error"
    at wrapError (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:10189:23) (/web/static/lib/owl/owl.js:2605)
    at onWillStart (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:10232:29) (/web/static/lib/owl/owl.js:2648)
    at useModel (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:63464:5) (/web/static/src/model/model.js:94)
    at FormController.setup (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:92084:31) (/web/static/src/views/form/form_controller.js:160)
    at FormController.setup (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:134831:15) (/mail/static/src/views/web/form/form_controller.js:10)
    at ComponentNode (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:9941:28) (/web/static/lib/owl/owl.js:2357)
    at https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:13345:28 (/web/static/lib/owl/owl.js:5761)
    at View.slot1 (eval at compile (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:13116:20), <anonymous>:15:36) (/web/static/lib/owl/owl.js:5532)
    at callSlot (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:10553:37) (/web/static/lib/owl/owl.js:2969)
    at WithSearch.template (eval at compile (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:13116:20), <anonymous>:8:12) (/web/static/lib/owl/owl.js:5532)

Caused by: RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:27834:19) (/web/static/src/core/network/rpc_service.js:37)
    at XMLHttpRequest.<anonymous> (https://acf-dev.newlogic-demo.com/web/assets/debug/web.assets_web.js:27882:27) (/web/static/src/core/network/rpc_service.js:85)

**SCREENSHOTS**:
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/782ca527-b674-4e4d-9167-a4044d598612)

**Comment by adriancris** [comment] 2024-04-30 12:27
@gonzalesedwin1123 

**ISSUE**: CR Agent can edit another CR Agent's created CR

**STEPS TO REPLICATE**:
1. Login as CR Agent 1 and create a CR.
2. Login as CR Agent 2 and make changes to CR Agent 1's created CR

**INSTANCE**: ACF-DEV

**SCREENSHOTS/SCREEN RECORDING**:
https://github.com/OpenSPP/openspp-modules/assets/138551361/4bd6de56-2275-4cd2-923d-9bd6d5ec0ce6

**Comment by adriancris** [comment] 2024-05-10 10:16
@gonzalesedwin1123 

Confirmed fixed:

- [Bug 1](https://github.com/OpenSPP/openspp-modules/issues/294#issuecomment-2081779553) 
https://github.com/OpenSPP/openspp-modules/assets/138551361/20dd0bcc-3e56-4044-af18-84ea4a9610e1

- [Bug 2](https://github.com/OpenSPP/openspp-modules/issues/294#issuecomment-2084301824)
https://github.com/OpenSPP/openspp-modules/assets/138551361/626c8745-17d4-4dac-b858-e6aa354c9760

- [Bug 3](https://github.com/OpenSPP/openspp-modules/issues/294#issuecomment-2085198625) 
https://github.com/OpenSPP/openspp-modules/assets/138551361/ee3c4d41-b401-46d6-b8ba-9df0e6d0aece

**Comment by adriancris** [comment] 2024-05-10 10:34
@gonzalesedwin1123

**ISSUE**: A local validator can reject another local validator's CR when its already assigned to the latter

**STEPS TO REPLICATE**:

1. Login as Validator Local 1.
2. Click Assign to Me.
3. Validate the CR.
4. Login as Validator Local 2.
5. Reject the CR assigned to Validator Local 1.

**INSTANCE**: ACF-DEV

**SCREENSHOTS/SCREEN RECORDING**:
https://github.com/OpenSPP/openspp-modules/assets/138551361/40c2d374-e255-4ce7-9443-699d1414fbb4

**Comment by emjay0921** [comment] 2024-07-22 07:02
I don't think this issues are related to this ticket @dasunhegoda .

**Comment by emjay0921** [comment] 2024-07-24 03:28
Added the Tests

**Closed as completed** 2024-07-24 14:43 UTC

**Comment by anthonymarkQA** [comment] 2024-07-25 06:21
Findings: returned to dev 

Add child CR type , the registrant input field is displaying individuals instead of groups.



![Image](https://github.com/user-attachments/assets/58a3bc70-6008-458a-bdfb-3a20911d972b)

**Comment by emjay0921** [comment] 2024-07-29 06:26
I already pushed the PR for this @anthonymarkQA

**Comment by anthonymarkQA** [comment] 2024-07-29 09:33
Findings: Returned to dev

When i select a CR type from the dropdown, an error message appears, blocking the whole testing of this ticket.
![image (13)](https://github.com/user-attachments/assets/3904e718-b0f7-48e1-afab-432d0bb54c05)

**Comment by anthonymarkQA** [comment] 2024-07-30 06:35
Findings: Returned to dev

Blocked, unable to approve via HQ level approver
![image](https://github.com/user-attachments/assets/df83bc3f-bf7a-4cc5-82fc-cfb5ea48d487)

**Comment by anthonymarkQA** [comment] 2024-08-01 07:17
Findings; Returned to DEV

Unable to validate in HQ level for CR type: Add Child
![image](https://github.com/user-attachments/assets/504eb234-c7a4-411f-a656-a1c55f40a544)
Unable to validate in HQ level for CR type: Change information
![image](https://github.com/user-attachments/assets/3eb8c661-8234-41c4-a471-1b4f78362616)

**Comment by emjay0921** [comment] 2024-08-01 07:56
## NEW PULL REQUEST: https://github.com/OpenSPP/openspp-modules/pull/497

## Why is this change needed?

To fix the applying error on different CR Types (Add Child and Change Info)

## How was the change implemented?

Added sudo() in write or create function to the update_live_data function of the CR Types.

## How to test manually...
- Install the CR Type module
- Create CR and go through the validation stages.
- Check if applied.

## Links
- https://github.com/orgs/OpenSPP/projects/5/views/4?pane=issue&itemId=50221529

## NOTES
sudo() were added to prevent the access rights issue in the applying stage of the CR. This is only added because we can't add the access rights of the said models on the error as the CR doesn't particularly connected to the said models. This happens because add child or change info and add farmer CR conflicts with each other.

**Comment by emjay0921** [comment] 2024-08-01 15:00
## UPDATE - DEPLOYED AND TESTED IN ACF-DEV INSTANCE

@anthonymarkQA I tested the CRs in the [acf-dev](https://acf-dev.newlogic-demo.com) and works good, you can test it now too.

## Why is this change needed?

- To fix the applying error on different CR Types (Add Child and Change Info)
- To remove the sudo() added on the previous PR

## How was the change implemented?

Remove the sudo() in write or create functions of the CR

## How to test manually...
- Install the CR Type module
- Create CR and go through the validation stages.
- Check if applied.

## Links
- https://github.com/orgs/OpenSPP/projects/5/views/4?pane=issue&itemId=50221529

## NOTES
Removed the sudo() as requested by @reichie020212 to prevent the bypassing of model security. Found the reason for the applying error in the ACF-DEV instance, the reasons are;
- Conflict in `spp_farmer_registry_base` with other CR Types (except for `spp_change_request_add_farmer`)
- Change Request Local and HQ Validator Access rights on `spp_farmer_registry_base` models were defined in `spp_change_request_add_farmer` (but in the acf-dev instance the `spp_change_request_add_farmer` is not installed, hence the error)

Conclusion:
- If `spp_farmer_registry_base` is really needed, we need to install the `spp_change_request_add_farmer` if we want to add other CR modules.

**Comment by anthonymarkQA** [comment] 2024-08-02 05:39
Findings: QA Passed

For change request and add child/member to work end to end. devs needed to add another CR type "Add farmer"
this is due to integrating farmer reg modules into an SPMIS instance. thus the limitation occurs.
![image](https://github.com/user-attachments/assets/2fe0fd38-88f3-4c94-baa1-1747360a7793)

Add child/member - pass
Add farmer - pass
Change information - pass
![image](https://github.com/user-attachments/assets/f84bcaf5-ada8-4e40-b780-9387efa0d09d)
![image](https://github.com/user-attachments/assets/0d10ed72-0493-46ed-bad3-186bcea2f67b)
