### ISSUE TITLE
Overwrite match only checks first data that matches the value

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#573] opened 2024-09-06 08:35 UTC
**Describe the bug**
Import match only checks the first data that it can find a match with. resulting to inconsistent data

**To Reproduce**

1. Login to sp-mis as admin
2. Go to Registry>configuration>Import match
3. Toggle on `overwrite match`
4. Use Contact for model field then use Name for field value 
5. Import a record with name already existing in registry (make sure this already existing name is duplicated in registry 2 or more)

**Expected behavior**
Module affected: spp_import_match
Context: Import match originally was used to match with unique values that is customer specific instead of using external IDs.

Import match therefore must update only unique from the registry upon import, if a duplicate is detected:

- it should raise an error upon clicking "test" during import process|
- it should raise an error upon clicking "import" during import process| and prevent import

In import match configuration. also hide the columns Match and Model

**Screenshots**

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by reichie020212** [comment] 2024-09-13 05:34
Estimate Dev Time

Optimistic: 8 hours
Pessimistic: 24 hours

**Comment by celinenilla** [comment] 2024-10-10 03:25
@singhkaranvir25 , can you please analyze what the actual expected behaviour should be for this ticket?

**Comment by anthonymarkQA** [comment] 2024-10-17 05:39
Action points:
Module affected: `spp_import_match`
Context: Import match originally was used to match with unique values that is customer specific instead of using external IDs.

Import match therefore must update only unique from the registry upon import, if a duplicate is detected:

-  it should raise an error upon clicking "test" during import process|
-  it should raise an error upon clicking "import" during import process| and prevent import


in import match configuration. also hide the columns `Match` and `Model`
![image](https://github.com/user-attachments/assets/6d3ae7dd-98a0-4dae-8174-6cc97cb7eedc)

cc: @singhkaranvir25 @celinenilla @emjay0921

**Comment by anjclarise** [comment] 2024-11-07 04:59
Verified this ticket and seems to be **not working as expected** for individuals import with matching names.  @emjay0921 cc: @celinenilla 

Test Steps:

1.  Install or Upgrade spp_import_match
2. Create an import match configuration for Contact (Registry > Configuration > Import Match)
3. Check overwrite match, and Add name in Fields.
4. Try importing with at least 2 existing duplicated name in Groups or Individuals.
5. If error was raised this PR is done.

Refer to screenshot below: 
Import match config page:
![Image](https://github.com/user-attachments/assets/e6e913b5-b7c7-4173-958e-71204513cde4)

Group Import for multiple name match: 
![Image](https://github.com/user-attachments/assets/d9a55d11-61d5-43c4-8b98-0983d405dc33)

Current list individuals list
![Image](https://github.com/user-attachments/assets/b735b717-c426-4fe9-bbcc-bfdfebaa41ab)

No error on individuals import page: (used data - test anj) 
![Image](https://github.com/user-attachments/assets/7ba80d54-227f-48b3-bc80-f4085a69de2e)

Data was imported successfully and the bank account number was added after the import: 
![Image](https://github.com/user-attachments/assets/de31da2e-7c2c-49bc-b2c5-f849171cc9e1)

**Comment by anthonymarkQA** [comment] 2024-11-07 06:20
Hi @anjclarise , i have tried it in individuals page and it seemed to work and gave an error message if it has multiple matches found in the registry>individuals page

kindly try importing this file in the same runboat instance you used

[Contact (res.partner) - 2024-11-07T141221.723.xlsx](https://github.com/user-attachments/files/17656896/Contact.res.partner.-.2024-11-07T141221.723.xlsx)

**Comment by anjclarise** [comment] 2024-11-07 07:13
Update: @anthonymarkQA and I tried the file from above, I get an error when I import the same file but when I used the same file and update the name field to an existing individual " ANJ, TEST" I didn't get an error. 

![Image](https://github.com/user-attachments/assets/b36ffd9e-61c3-42ca-bf9f-307b59fdd145)

We suspect that this could be because I edit the file using googlesheet >> download the file as .xlsx format >> then import to openspp in the individual page. Unlike @anthonymarkQA who uses libre office 

cc: @celinenilla @emjay0921

**Comment by emjay0921** [comment] 2024-11-11 02:27
I'll check this one.

**Comment by emjay0921** [comment] 2024-11-14 10:53
@anjclarise can you upload here a video screen recording of the issue? Also upload here the excel or csv files you used. Thank you.

**Comment by emjay0921** [comment] 2024-11-15 10:38
@kneckinator , @reichie020212 , @gonzalesedwin1123 , @celinenilla , @anjclarise 

Found the issue of this when using `name` field for import match on Individual, so the problem is the `name_change` function in `g2p_registry_individual` is adding a whitespace or a blank space after the `given_name`. So Import Match can't search it properly as it is case sensitive.

e.g. 
Family Name: "Dela Cruz"
Given Name: "Juan"

Output of Name field is: "DELA CRUZ, JUAN " (notice the space, also this is automatically converted to Uppercase)

So new PR: https://github.com/OpenSPP/openg2p-registry/pull/4 in g2p_registry forked repository to fix this, on which it will retain making it in Uppercase but not adding a blank space.

Please review @reichie020212 , @kneckinator , @gonzalesedwin1123 .

**Comment by kneckinator** [comment] 2024-11-18 02:40
@celinenilla should this also be released as a fix on top of Batanes (17.0.1.2.1), or do we only put this in 17.0.1.3.1?

**Comment by kneckinator** [comment] 2024-11-19 02:02
I linked this issue to the PR in the OpenSPP-OpenG2P-Registry fork and it is now ready for review again.

**Comment by anthonymarkQA** [comment] 2024-11-20 08:17
Findings: Returned to dev
Tested in runboat. 
branch 17.0 
repo: openspp/openspp-modules

I cannot replicate the fixes, importing a name that already exists more than one in the registry does not display any error
![image](https://github.com/user-attachments/assets/081183a4-bd4e-4774-926c-b9960e89d63d)

Also the match and model columns in import match is still not being hidden
![image](https://github.com/user-attachments/assets/1ca9e44b-e219-4b4a-b14d-4955fe383ed6)

**Comment by anthonymarkQA** [comment] 2024-11-20 10:13
Findings: QA Passed
tested in runboat
branch: 573-overwrite-match-fix
Repo: openspp/openspp-modules

when importing individuals with duplicates existing 2 or more records - pass
![image](https://github.com/user-attachments/assets/eff11b40-5a6a-4d84-be00-fa4e20fd7c40)

when importing groups with duplicates existing 2 or more records - pass
![image](https://github.com/user-attachments/assets/fb06f42f-d215-4989-95eb-3b709ed28c6e)

Remove match and model column in import match - pass
![image](https://github.com/user-attachments/assets/fd97803c-471e-4b1b-a9b0-1075a3a36274)

**Closed as completed** 2024-11-21 03:45 UTC
Labels: bug
