### ISSUE TITLE
Adjust support for Async import in odoo17

### ISSUE THREAD

**Issue by jannahadlaon** [openspp-project/openspp-registry#534] opened 2024-08-19 08:03 UTC
**Describe the bug**

**To Reproduce**
**Actual behavior**
When attempting to do an import, the checkbox "import in the background" is not present in the UI

**Expected behavior**

1. "import in the background" checkbox should be visible
2. Using import in the background allows user to exit the current page while import is ongoing.
3. prepare 1k lines of registrants in a csv then use import in the background during upload
**Screenshots**
![Image](https://github.com/user-attachments/assets/224b16c2-3b60-490d-b939-132055fd1162)
**Additional context**
This ticket was previously logged in the link below from a repository that has been archived:
[https://github.com/OpenSPP/openspp-acf/issues/35](https://github.com/OpenSPP/openspp-acf/issues/35)

**Comment by emjay0921** [comment] 2024-08-28 00:13
https://github.com/OpenSPP/openspp-modules/pull/518 here's the PR for this which is already Merged and Deployed.
You might need to install or upgrade `spp_import_match` module.

## Notes
There's a change on the behavior of this, it will automatically set itself to async if the record being imported is more than 100. There's a major changes in odoo import so it will take time to add the checkbox. So I made it automatically for now.

**Comment by jannahadlaon** [comment] 2024-09-03 06:48
Issue is still present. See video in the link:
[https://newlogic.slack.com/archives/C05FF1V3V0B/p1725271755181609](https://newlogic.slack.com/archives/C05FF1V3V0B/p1725271755181609)

**Comment by jannahadlaon** [comment] 2024-09-25 06:17
Findings: Issue is still present in [SP-MIS](http://openspp-openspp-modules-deploy-534-4e87d9edce8b.runboatk8.newlogic-demo.com/web#action=332&model=res.partner&view_type=list&cids=1&menu_id=219)

**Steps**:

1. Install spp_import_match module.
![image](https://github.com/user-attachments/assets/c968d5c6-7ea8-490d-a00f-64fb2a79995b)
2. Go to Registry >> Groups >> Import records
3. Import CSV with 1k registrants
4. See issue:
![image](https://github.com/user-attachments/assets/2c98fe7b-12ce-4e14-8660-103fd3f88daa)

cc: @Markpenalosa @emjay0921

**Comment by emjay0921** [comment] 2024-10-07 03:53
I think the Job Queue is not being initialized on runboat so we might need to restart Odoo when Job Queue is installed. So that @jannahadlaon can continue the test.

cc: @kneckinator

**Comment by jannahadlaon** [comment] 2024-10-09 06:38
Findings: Returned to dev

Connected to:
https://github.com/OpenSPP/openspp-modules/issues/622

**Comment by celinenilla** [comment] 2024-10-28 02:30
@jannahadlaon, can you please retest this on spmis qa and see if the issue is solved?

**Comment by jannahadlaon** [comment] 2024-10-28 09:35
Findings: **QA PASSED**

Steps:

1. Install spp_import_match module.
2. Install Starter for SP-MIS
3. Go to Registry >> Groups >> Import records
4. Import CSV with 1k registrants - verify that import is successful and data is correct
_Video:_ [TEST-534](https://drive.google.com/file/d/1F6dTKt7W5KqJr21NURq87R3bagbdbkXT/view?usp=sharing)
![image](https://github.com/user-attachments/assets/bec9cd6b-e9a0-4888-b975-a8148633b07e)

**Closed as completed** 2024-11-11 03:28 UTC
Labels: bug
